// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB29gApOtU10qO9G1DgLQq84rBmY3Xq7mI',
    appId: '1:423787838818:web:75e2553613f333fcefc03b',
    messagingSenderId: '423787838818',
    projectId: 'thrivebynightdev-866d3',
    authDomain: 'thrivebynightdev-866d3.firebaseapp.com',
    storageBucket: 'thrivebynightdev-866d3.appspot.com',
    measurementId: 'G-RW01TQ8H8G',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbkH1dwyOCKCrxtKXU3VUSc-1Y9E63C-k',
    appId: '1:423787838818:ios:95fa39a10b6ef5cdefc03b',
    messagingSenderId: '423787838818',
    projectId: 'thrivebynightdev-866d3',
    storageBucket: 'thrivebynightdev-866d3.appspot.com',
    iosClientId: '423787838818-0famitb23e2vbbc73hatun86dvp2oaoj.apps.googleusercontent.com',
    iosBundleId: 'com.mezalabs.thrivebynightdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbkH1dwyOCKCrxtKXU3VUSc-1Y9E63C-k',
    appId: '1:423787838818:ios:95fa39a10b6ef5cdefc03b',
    messagingSenderId: '423787838818',
    projectId: 'thrivebynightdev-866d3',
    storageBucket: 'thrivebynightdev-866d3.appspot.com',
    iosClientId: '423787838818-0famitb23e2vbbc73hatun86dvp2oaoj.apps.googleusercontent.com',
    iosBundleId: 'com.mezalabs.thrivebynightdev',
  );
}
